"""
Step 4 & 5: 최종 GuruNote 마크다운 조립 + 파일명 sanitize + autosave.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Optional

from gurunote.types import Transcript, _format_ts

# autosave 기본 경로
AUTOSAVE_DIR = Path.cwd() / "autosave"


def sanitize_filename(name: str, max_len: int = 80) -> str:
    """
    영상 제목을 파일명으로 안전하게 변환.
    `GuruNote_<영상제목>.md` 의 가운데 부분에 그대로 들어간다.
    """
    if not name:
        return "untitled"
    cleaned = re.sub(r"[\\/:*?\"<>|]", "", name)
    cleaned = re.sub(r"\s+", "_", cleaned).strip("._")
    if len(cleaned) > max_len:
        cleaned = cleaned[:max_len].rstrip("._")
    return cleaned or "untitled"


def build_full_script_section(translated_text: str) -> str:
    """번역된 스크립트를 마크다운 섹션으로 감싼다."""
    return "# 📝 전체 스크립트 번역본\n\n" + translated_text.strip() + "\n"


def build_original_script_section(transcript: Transcript) -> str:
    """영어 원문 스크립트 섹션 (참고용)."""
    lines = ["# 🇺🇸 영어 원문 스크립트", ""]
    for seg in transcript.segments:
        ts = _format_ts(seg.start)
        lines.append(f"**[{ts}] Speaker {seg.speaker}:** {seg.text}")
        lines.append("")
    return "\n".join(lines)


def build_chapters_section(chapters: Iterable) -> str:
    """
    영상 챕터 섹션. `chapters` 는 `Chapter` 객체 또는 dict 리스트.
    빈 경우 빈 문자열을 반환해 호출자가 skip 가능.
    """
    items = list(chapters or [])
    if not items:
        return ""
    lines = ["# ⏱️ 원본 영상 챕터", ""]
    for ch in items:
        if hasattr(ch, "start"):
            start, title = ch.start, ch.title  # type: ignore[union-attr]
        else:
            start, title = ch.get("start", 0), ch.get("title", "")  # type: ignore[union-attr]
        lines.append(f"- `[{_format_ts(float(start))}]` {title}")
    lines.append("")
    return "\n".join(lines)


def build_gurunote_markdown(
    title: str,
    webpage_url: str,
    summary_md: str,
    translated_text: str,
    transcript: Transcript,
    uploader: str | None = None,
    stt_engine: str = "",
    upload_date: Optional[str] = None,
    chapters: Optional[Iterable] = None,
    subtitles_source: str = "",
    # Phase A — 지식 증류기 메타데이터
    organized_title: str = "",
    field: str = "",
    tags: Optional[List[str]] = None,
) -> str:
    """
    최종 다운로드용 마크다운 조립.

    구조:
        - YAML frontmatter (Obsidian/Notion 호환 — Phase A)
        - 헤더 (영상 메타: 제목/채널/게시일/URL/STT/화자수/재생시간/분야/태그)
        - 원본 영상 챕터 (있을 경우)
        - GuruNote 요약 (LLM 결과)
        - 전체 번역 스크립트
        - 영어 원문 스크립트
        - 푸터
    """
    display_title = (organized_title or title).strip()

    # YAML frontmatter — Obsidian/Notion 가 자동 인식하는 메타. 비어있으면 생략.
    frontmatter = _build_frontmatter(
        organized_title=organized_title or title,
        original_title=title,
        uploader=uploader or "",
        upload_date=upload_date or "",
        webpage_url=webpage_url,
        field=field,
        tags=tags or [],
        stt_engine=stt_engine,
        duration_sec=transcript.duration,
        num_speakers=len(transcript.speakers),
    )

    meta_lines = [f"# 🎙️ GuruNote — {display_title}", ""]
    if organized_title and organized_title != title:
        meta_lines.append(f"- **원본 제목:** {title}")
    if uploader:
        meta_lines.append(f"- **채널:** {uploader}")
    if upload_date:
        meta_lines.append(f"- **게시일:** {upload_date}")
    meta_lines.append(f"- **원본 영상:** <{webpage_url}>")
    if field:
        meta_lines.append(f"- **분야:** {field}")
    if tags:
        tag_str = " ".join(f"`#{t}`" for t in tags)
        meta_lines.append(f"- **태그:** {tag_str}")
    if stt_engine:
        meta_lines.append(f"- **STT 엔진:** `{stt_engine}`")
    if subtitles_source:
        meta_lines.append(f"- **참고한 기존 자막:** `{subtitles_source}`")
    meta_lines.append(f"- **화자 수:** {len(transcript.speakers)}")
    if transcript.duration:
        meta_lines.append(f"- **재생 시간:** {_format_ts(transcript.duration)}")
    meta_lines.append("")

    chapters_section = build_chapters_section(chapters or [])

    parts: list[str] = []
    if frontmatter:
        parts.extend([frontmatter, ""])
    parts.append("\n".join(meta_lines))
    if chapters_section:
        parts.extend([chapters_section, ""])
    parts.extend([
        summary_md.strip(),
        "",
        build_full_script_section(translated_text),
        "",
        build_original_script_section(transcript),
        "",
        "---",
        "_Generated by **GuruNote** — Powered by WhisperX · OpenAI / Anthropic · yt-dlp_",
        "",
    ])
    return "\n".join(parts)


def _build_frontmatter(
    *,
    organized_title: str,
    original_title: str,
    uploader: str,
    upload_date: str,
    webpage_url: str,
    field: str,
    tags: List[str],
    stt_engine: str,
    duration_sec: float,
    num_speakers: int,
) -> str:
    """
    Obsidian / Notion / Hugo / Jekyll 호환 YAML frontmatter.

    필요한 값이 하나도 없으면 빈 문자열 반환.
    """
    if not (organized_title or field or tags):
        return ""

    lines: list[str] = ["---"]
    if organized_title:
        # YAML safe quoting: 콜론/대시/특수문자 안전
        lines.append(f'title: "{_yaml_escape(organized_title)}"')
    if original_title and original_title != organized_title:
        lines.append(f'original_title: "{_yaml_escape(original_title)}"')
    if uploader:
        lines.append(f'uploader: "{_yaml_escape(uploader)}"')
    if upload_date:
        lines.append(f"upload_date: {upload_date}")
    if webpage_url:
        lines.append(f"source_url: {webpage_url}")
    if field:
        lines.append(f'field: "{_yaml_escape(field)}"')
    if tags:
        # Obsidian 스타일: 공백/특수문자 없는 단순 태그
        sanitized = [_yaml_tag(t) for t in tags]
        sanitized = [t for t in sanitized if t]
        if sanitized:
            tag_array = ", ".join(f'"{t}"' for t in sanitized)
            lines.append(f"tags: [{tag_array}]")
    if stt_engine:
        lines.append(f'stt_engine: "{stt_engine}"')
    if duration_sec:
        lines.append(f"duration_sec: {int(duration_sec)}")
    if num_speakers:
        lines.append(f"num_speakers: {num_speakers}")
    lines.append(f'created: {datetime.now().isoformat(timespec="seconds")}')
    lines.append("---")
    return "\n".join(lines)


def _yaml_escape(value: str) -> str:
    """YAML 큰따옴표 문자열 이스케이프 — 백슬래시/큰따옴표만."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _yaml_tag(value: str) -> str:
    """Obsidian 호환 태그 정규화 — 공백을 `_`로, `#` 앞쪽 prefix 제거."""
    v = value.strip().lstrip("#").strip()
    return re.sub(r"\s+", "_", v)


def autosave_result(full_md: str, title: str, save_dir: Path | None = None) -> Path:
    """
    파이프라인 완료 후 full_md 를 autosave/ 폴더에 자동 저장.
    파일명: GuruNote_<title>_<YYYYMMDD_HHMMSS>.md
    Returns: 저장된 파일 경로.
    """
    out_dir = save_dir or AUTOSAVE_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    fname = f"GuruNote_{sanitize_filename(title)}_{ts}.md"
    path = out_dir / fname
    path.write_text(full_md, encoding="utf-8")
    return path
