"""
Step 4 & 5: 최종 GuruNote 마크다운 조립 + 파일명 sanitize.
"""

from __future__ import annotations

import re
from typing import Iterable, Optional

from gurunote.types import Transcript, _format_ts


def sanitize_filename(name: str, max_len: int = 80) -> str:
    """
    영상 제목을 파일명으로 안전하게 변환.
    `GuruNote_<영상제목>.md` 의 가운데 부분에 그대로 들어간다.
    """
    if not name:
        return "untitled"
    cleaned = re.sub(r"[\\/:*?\"<>|]", "", name)
    cleaned = re.sub(r"\s+", "_", cleaned).strip("._")
    if len(cleaned) > max_len:
        cleaned = cleaned[:max_len].rstrip("._")
    return cleaned or "untitled"


def build_full_script_section(translated_text: str) -> str:
    """번역된 스크립트를 마크다운 섹션으로 감싼다."""
    return "# 📝 전체 스크립트 번역본\n\n" + translated_text.strip() + "\n"


def build_original_script_section(transcript: Transcript) -> str:
    """영어 원문 스크립트 섹션 (참고용)."""
    lines = ["# 🇺🇸 영어 원문 스크립트", ""]
    for seg in transcript.segments:
        ts = _format_ts(seg.start)
        lines.append(f"**[{ts}] Speaker {seg.speaker}:** {seg.text}")
        lines.append("")
    return "\n".join(lines)


def build_chapters_section(chapters: Iterable) -> str:
    """
    영상 챕터 섹션. `chapters` 는 `Chapter` 객체 또는 dict 리스트.
    빈 경우 빈 문자열을 반환해 호출자가 skip 가능.
    """
    items = list(chapters or [])
    if not items:
        return ""
    lines = ["# ⏱️ 원본 영상 챕터", ""]
    for ch in items:
        if hasattr(ch, "start"):
            start, title = ch.start, ch.title  # type: ignore[union-attr]
        else:
            start, title = ch.get("start", 0), ch.get("title", "")  # type: ignore[union-attr]
        lines.append(f"- `[{_format_ts(float(start))}]` {title}")
    lines.append("")
    return "\n".join(lines)


def build_gurunote_markdown(
    title: str,
    webpage_url: str,
    summary_md: str,
    translated_text: str,
    transcript: Transcript,
    uploader: str | None = None,
    stt_engine: str = "",
    upload_date: Optional[str] = None,
    chapters: Optional[Iterable] = None,
    subtitles_source: str = "",
) -> str:
    """
    최종 다운로드용 마크다운 조립.

    구조:
        - 헤더 (영상 메타: 제목/채널/게시일/URL/STT/화자수/재생시간)
        - 원본 영상 챕터 (있을 경우)
        - GuruNote 요약 (LLM 결과)
        - 전체 번역 스크립트
        - 영어 원문 스크립트
        - 푸터
    """
    meta_lines = [f"# 🎙️ GuruNote — {title}", ""]
    if uploader:
        meta_lines.append(f"- **채널:** {uploader}")
    if upload_date:
        meta_lines.append(f"- **게시일:** {upload_date}")
    meta_lines.append(f"- **원본 영상:** <{webpage_url}>")
    if stt_engine:
        meta_lines.append(f"- **STT 엔진:** `{stt_engine}`")
    if subtitles_source:
        meta_lines.append(f"- **참고한 기존 자막:** `{subtitles_source}`")
    meta_lines.append(f"- **화자 수:** {len(transcript.speakers)}")
    if transcript.duration:
        meta_lines.append(f"- **재생 시간:** {_format_ts(transcript.duration)}")
    meta_lines.append("")

    chapters_section = build_chapters_section(chapters or [])

    parts = [
        "\n".join(meta_lines),
    ]
    if chapters_section:
        parts.extend([chapters_section, ""])
    parts.extend([
        summary_md.strip(),
        "",
        build_full_script_section(translated_text),
        "",
        build_original_script_section(transcript),
        "",
        "---",
        "_Generated by **GuruNote** — Powered by WhisperX · OpenAI / Anthropic · yt-dlp_",
        "",
    ])
    return "\n".join(parts)
